regions:
    highlighted: Highlighted
    content_top: 'Content top'
    content: 'Content'
    sidebar_first: 'Sidebar first'
    sidebar_second: 'Sidebar second'
    content_bottom: 'Content bottom'
