# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.website_token_authenticator:
        class: CoreBundle\Security\WebsiteUserTokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager']
    app.admin_token_authenticator:
        class: CoreBundle\Security\AdminUserTokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager']