<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FriendlyUrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendlyUrlRepository extends EntityRepository
{
}
